 const REQUEST_STATUS_CREATED = 0;
 const REQUEST_STATUS_ON_NEGOTIATION = 1;
 const REQUEST_STATUS_PAID = 2;
 const REQUEST_STATUS_ON_DELIVERY = 3;
 const REQUEST_STATUS_DONE = 4;

 const REQUEST_STATUS_ARR = [REQUEST_STATUS_CREATED,
    REQUEST_STATUS_ON_NEGOTIATION,
    REQUEST_STATUS_PAID,
    REQUEST_STATUS_DONE
];

 const SYSTEM_ROLE = {
    ADMIN: 'admin',
    USER: 'user'
};

 const SYSTEM_ROLE_ARR = [
    SYSTEM_ROLE.ADMIN,
    SYSTEM_ROLE.USER,
];

 const SYSTEM_STATUS = {
    ACTIVE: 'active',
    BLOCKED: 'blocked'
};

 const SYSTEM_STATUS_ARR = [
    SYSTEM_STATUS.ACTIVE,
    SYSTEM_STATUS.BLOCKED,
];

module.exports = {
    REQUEST_STATUS_CREATED: REQUEST_STATUS_CREATED,
    REQUEST_STATUS_ON_NEGOTIATION: REQUEST_STATUS_ON_NEGOTIATION,
    REQUEST_STATUS_PAID: REQUEST_STATUS_PAID,
    REQUEST_STATUS_ON_DELIVERY: REQUEST_STATUS_ON_DELIVERY,
    REQUEST_STATUS_DONE: REQUEST_STATUS_DONE,
    REQUEST_STATUS_ARR: REQUEST_STATUS_ARR,
    SYSTEM_ROLE: SYSTEM_ROLE,
    SYSTEM_ROLE_ARR: SYSTEM_ROLE_ARR,
    SYSTEM_STATUS: SYSTEM_STATUS,
    SYSTEM_STATUS_ARR: SYSTEM_STATUS_ARR
}


