# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: [self-hosted, scan-kiz-back-prod]
    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    env:
      NODE_ENV: production
      JWT_SECRET: ${{secrets.KIZ_SCAN_BACKEND_JWT_SECRET}}
      MAIN_URL: ${{secrets.MAIN_URL}}
    steps:
      - name: Copy config file to temp folder
      run: cp /www/wwwroot/scan_kiz_be/config/config.json ~/project/temp/scan_kiz_back/config.json
    # - name: Archive config file
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: config-file
    #     path: config/config.json
    # - name: Copy production folder to server
    #   run: scp -r public/uploads/ root@45.77.67.220:/www/wwwroot/cicd/temp/

    # - name: Copy config file to server
    #   run: scp config/config.json root@45.77.67.220:/www/wwwroot/cicd/temp/
    - uses: actions/checkout@v3
      with:
        ref: 'master'
    - name: Restore config file from temp folder
      run: cp ~/project/temp/scan_kiz_back/config.json /www/wwwroot/scan_kiz_be/config/config.json
    # - name: Restore config file
    #   uses: actions/download-artifact@v2
    #   with:
    #     name: config-file
    #     path: config
    - name: Delete artifact config file
      uses: geekyeggo/delete-artifact@v5
      with:
        name: config-file
    - name: Create .env file
      run: echo "NODE_ENV=production" > .env
    - name: Update jwt secret .env
      run: echo "JWT_SECRET=${{secrets.KIZ_SCAN_BACKEND_JWT_SECRET}}" >> .env
      - name: Update main_url .env
      run: echo "MAIN_URL=${{secrets.MAIN_URL}}" >> .env
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Migrate to database
      run: npx sequelize-cli db:migrate --env=production
    - run: npm i --init-module
    - name: Run reexecute.sh
      run: bash .github/workflows/reexecute.sh

    # - run: npm run build --if-present
    # - name: Install pm2
    #   run: npm install pm2 -g

    # - name: Install nodemon
    #   run: npm install -g nodemon
    # - name: Set nodemon Path
    #   run: npm install --save-dev nodemon
    # - name: Install Babel and related dependencies
    #   run: |
    #     npm install --save-dev @babel/core @babel/node @babel/preset-env
  
    # - name: Stop application if running
    #   run: npx pm2 delete "kiz-scan-back" || true
    # - name: Start application with pm2
    #   run: npx pm2 start app.js --name "kiz-scan-back"
    # - name: Copy example config to config.json
    #   run: cp ./config/.example.config ./config/config.json

