# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: [self-hosted, scan-kiz-back-dev]
    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    env:
      NODE_ENV: production
      JWT_SECRET: ${{secrets.KIZ_SCAN_BACKEND_JWT_SECRET}}
      MAIN_URL: ${{secrets.KIZ_SCAN_BACKEND_MAIN_URL}}
    steps:
    - name: Copy config file to temp folder
      run: cp /www/wwwroot/runners/scan_kiz_be_dev/scan_kiz_backend/scan_kiz_backend/config/config.json /project/temp/scan_kiz_back_dev/config.json
      continue-on-error: true
    - uses: actions/checkout@v3
      with:
        ref: 'develop'
    - name: Restore config file from temp folder
      run: cp /project/temp/scan_kiz_back_dev/config.json /www/wwwroot/runners/scan_kiz_be_dev/scan_kiz_backend/scan_kiz_backend/config/config.json
      continue-on-error: true
    - name: Create .env file
      run: echo "NODE_ENV=production" > .env
    - name: Update jwt secret .env
      run: echo "JWT_SECRET=${{secrets.KIZ_SCAN_BACKEND_JWT_SECRET}}" >> .env
    - name: Update main_url .env
      run: echo "MAIN_URL=${{secrets.KIZ_SCAN_BACKEND_MAIN_URL}}" >> .env
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm i --init-module
    - run: npm run build --if-present
    - name: Migrate to database
      run: npx sequelize-cli db:migrate --env=production
    - name: Run reexecute.sh
      run: bash .github/workflows/reexecute.sh